### ISSUE TITLE
optional log channel

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge#10]
please make the log channel optional.
if it can be done make this fo "mongodb" too :)

thank you for awesome bot

**Comment by em108** [comment]
Yes, please. If there could be a way where one could choose to run the bot without the mongo dB. It would be great. Say you mostly use the gdrive features and other basic features that don't involve the dB use.
Special thanks you for the time you've taken into the userbot developers!

**Comment by K-E-N-W-A-Y** [comment]
log channel is optional, but we can't make MongoDB optional we use DB to store data related to bot tasks

**Comment by qorcfotian** [comment]
> log channel is optional, but we can't make MongoDB optional we use DB to store data related to bot tasks

how to disable log channel?

**Comment by K-E-N-W-A-Y** [comment]
> > log channel is optional, but we can't make MongoDB optional we use DB to store data related to bot tasks
> 
> how to disable log channel?

add `0` to bot channel id value field

**Comment by em108** [comment]
Is it possible to use a local database like SQlite instead of mongoDB?
