### ISSUE TITLE
Link shortening api

### ISSUE THREAD

**Issue by nischay03654** [UsergeTeam/Userge#101]
Isn't it cool of u add some api's to short link through userbot...
Example:
.shorturl [url]

**Comment by udaythefreelancer** [comment]
there is already a module on that in telethon i think @rking32  might port it :-)

**Comment by Phyco-Ninja** [comment]
Hmmmm

**Comment by rking32** [comment]
@Phyco-Ninja #idea

**Comment by Phyco-Ninja** [comment]
*_*
