### ISSUE TITLE
Downloading files to specific folder

### ISSUE THREAD

**Issue by nischay03654** [UsergeTeam/Userge#102]
Is there any command to download files to google drive specific folder.. if we use .gup the file is downloaded in default folder....

Let me explain: assume there is a folder named movies in my default drive directory... So instead of downloading files to the default directory and moving it on movies folder is there any command to do this directly?

**Comment by rking32** [comment]
did you ever try `.gset`

**Comment by nischay03654** [comment]
> did you ever try `.gset`

I tried but Everytime I want to download some specific files I have to set download folder to others... Isn't there a way to do this like:

.gup movie.mp4 | movies(folder name)

**Comment by rking32** [comment]
> > did you ever try `.gset`
> 
> I tried but Everytime I want to download some specific files I have to set download folder to others... Isn't there a way to do this like:
> 
> .gup movie.mp4 | movies(folder name)

no, you have to use `.gset`
