### ISSUE TITLE
Seed.cc link error

### ISSUE THREAD

**Issue by cloudoftg** [UsergeTeam/Userge#103]
Can't download files from seedr.cc it download some part of the file and then again start from the beginning again and again and at the end it says "provide in valid file path" Any solution

**Comment by pboy192** [comment]
> Can't download files from seedr.cc it download some part of the file and then again start from the beginning again and again and at the end it says "provide in valid file path" Any solution

Did u tried the direct file link like https://example.com/example.pdf or just normal forwarding link?

**Comment by cloudoftg** [comment]
the link look like this https://fr8.seedr.cc/ff_get/706057437/Sonic.the.hedgehog.2020.1080p-dual-lat-cinecalidad.is.mp4?st=dcTV0v__4nJF2QlhsjDY1Q&e=1595034758 
so?

**Comment by rking32** [comment]
> Can't download files from seedr.cc it download some part of the file and then again start from the beginning again and again and at the end it says "provide in valid file path" Any solution

try `.term wget [link]`

**Comment by cloudoftg** [comment]
did that wont work.

**Comment by cloudoftg** [comment]
Seedr.cc link doesnt work at all. After few tries it says invalid path provided.

**Comment by rking32** [comment]
yes, many users have reported it and gonna implement other library better than `SmartDL`

**Comment by rking32** [comment]
moving this to #58
