### ISSUE TITLE
Bug in .ytdl

### ISSUE THREAD

**Issue by code-rgb** [UsergeTeam/Userge#105]
**Not Able the Download Youtube video audio by .ytdl**

`.ytdl -m -t link will upload the mp3` - this has some issues.

Also youtube-dl via command line works perfectly fine `.term youtube-dl -x --audio-format mp3 URL`

**Comment by Harsh-br0** [comment]
> **Not Able the Download Youtube video audio by .ytdl**
> 
> `.ytdl -m -t link will upload the mp3` - this has some issues.
> 
> Also youtube-dl via command line works perfectly fine `.term youtube-dl -x --audio-format mp3 URL`

Buddy , its even not working for me too by term
Cuz its not by devs , 
Depends on source devs of ytdl (－－〆)

**Comment by code-rgb** [comment]
It sure works by term check chat

**Comment by Harsh-br0** [comment]
> It sure works by term check chat

[checked buddy (¯―¯٥)](https://telegra.ph/file/0b2821bb0153e2a742649.jpg)

**Comment by viper-adnan** [comment]
`.ytdl -g {url}`

Also add a flag `-g` for download youtube video and upload it to Google Drive.

**Comment by rking32** [comment]
> `.ytdl -g {url}`
> 
> Also add a flag `-g` for download youtube video and upload it to Google Drive.

why you can't do it manually ?
every things you need to be automated ?
