### ISSUE TITLE
Bot is Not getting started

### ISSUE THREAD

**Issue by Nenokkadine** [UsergeTeam/Userge#106]
![image](https://user-images.githubusercontent.com/65813999/88249886-6695be00-ccc3-11ea-9f09-ba3dfb65767c.png)
I Updated the bot to latest alpha and it shows this in the chat I haven't changed anything

**Comment by lacyboi** [comment]
Add bot to your log channel and restrt and kinnda join @usergeot in telegram for such kinnda queries

**Comment by lacyboi** [comment]
> ![image](https://user-images.githubusercontent.com/65813999/88249886-6695be00-ccc3-11ea-9f09-ba3dfb65767c.png)
> I Updated the bot to latest alpha and it shows this in the chat I haven't changed anything

.

**Comment by Nenokkadine** [comment]
Thanks got it

**Comment by Rayanfer32** [comment]
> 
> 
> Thanks got it

How did u fix it...plz help ?

**Comment by Nenokkadine** [comment]
> > Thanks got it
> 
> How did u fix it...plz help ?

Add bot to your log channel
