### ISSUE TITLE
Unpack .7z files

### ISSUE THREAD

**Issue by theRay1s** [UsergeTeam/Userge#112]
Add support for unpacking .7z Files

**Comment by rking32** [comment]
7z files don't use regularly (so rarely). anyway u can try `term` to do that task.

**Comment by theRay1s** [comment]
@rking32 how can u explain the command

**Comment by rking32** [comment]
> @rking32 how can u explain the command

`7z x <file_name>.7z` to extract files.

**Comment by theRay1s** [comment]
@rking32 u14439:~$ 7z x "downloads/The Umbrella Academy S02 1080p NF WEB-DL Hindi - English DD 5.1 H264 ~Ranvijay.7z"
/app/.apt/usr/bin/7z: 2: exec: /usr/lib/p7zip/7z: not found

**Comment by rking32** [comment]
> @rking32 u14439:~$ 7z x "downloads/The Umbrella Academy S02 1080p NF WEB-DL Hindi - English DD 5.1 H264 ~Ranvijay.7z"
> /app/.apt/usr/bin/7z: 2: exec: /usr/lib/p7zip/7z: not found

are you using latest ?

**Comment by rking32** [comment]
@theRay1s found a solution
try `.apt/usr/lib/p7zip/7z x <file_name>.7z`
so `.term .apt/usr/lib/p7zip/7z x <file_name>.7z` :+1:
