### ISSUE TITLE
Missing/Can't Load Unofficial Plugins

### ISSUE THREAD

**Issue by GlgApr** [UsergeTeam/Userge#115]
some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
I tried to change it to false then true but still not there. can you give an explanation?
And this is the log:
https://del.dog/wybokithyf
![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)

**Comment by UdaySriHarsha** [comment]
have u updated the bot

**Comment by GlgApr** [comment]
updated?
already try restart the bot

**Comment by Harsh-br0** [comment]
> some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> I tried to change it to false then true but still not there. can you give an explanation?
> And this is the log:
> https://pastebin.com/b6WZbCc4
> ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)

Use dogbin or nekobin next time , its difficult to find that particular thing in that 🤕

**Comment by GlgApr** [comment]
thank you, updated to dogbin
https://del.dog/wybokithyf

**Comment by UdaySriHarsha** [comment]
me getting the too after latest update

**Comment by GlgApr** [comment]
which version are you using?
and how to updated the bot?

**Comment by UdaySriHarsha** [comment]
> which version are you using?
> and how to updated the bot?

me latest
update command - ```.update -alpha -pull -push```

**Comment by GlgApr** [comment]
oke, i will try it

**Comment by Harsh-br0** [comment]
> thank you, updated to dogbin
> https://del.dog/wybokithyf

[Glad to see this](https://telegra.ph/file/a37a30cc9dedbaacc461d.jpg) 😬

**Comment by Krishna-Singhal** [comment]
> some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> I tried to change it to false then true but still not there. can you give an explanation?
> And this is the log:
> https://del.dog/wybokithyf
> ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)

Do simply `.update -alpha -pull -push` and `.restart -h` after update

I am sure you is not on latest, [see this](https://telegra.ph/file/7ab51b34c7a380c798691.jpg)

**Comment by UdaySriHarsha** [comment]
> > some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> > I tried to change it to false then true but still not there. can you give an explanation?
> > And this is the log:
> > https://del.dog/wybokithyf
> > ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)
> 
> Do simply `.update -alpha -pull -push` and `.restart -h` after update
> 
> I am sure you is not on latest, [see this](https://telegra.ph/file/7ab51b34c7a380c798691.jpg)

even me getting the problem, I'm on latest ```0.1.7-staging.13```

**Comment by Krishna-Singhal** [comment]
> > > some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> > > I tried to change it to false then true but still not there. can you give an explanation?
> > > And this is the log:
> > > https://del.dog/wybokithyf
> > > ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)
> > 
> > 
> > Do simply `.update -alpha -pull -push` and `.restart -h` after update
> > I am sure you is not on latest, [see this](https://telegra.ph/file/7ab51b34c7a380c798691.jpg)
> 
> even me getting the problem, I'm on latest `0.1.7-staging.13`

Do restart 🤔

**Comment by GlgApr** [comment]
> > some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> > I tried to change it to false then true but still not there. can you give an explanation?
> > And this is the log:
> > https://del.dog/wybokithyf
> > ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)
> 
> Do simply `.update -alpha -pull -push` and `.restart -h` after update
> 
> I am sure you is not on latest, [see this](https://telegra.ph/file/7ab51b34c7a380c798691.jpg)

I waited for the deployment process, more than 3 minutes. then did -restart -h, but there was no response. in heroku has been successfully deployed, but the log displays a message like this

https://del.dog/vyfephalyc

**Comment by Krishna-Singhal** [comment]
> > > some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> > > I tried to change it to false then true but still not there. can you give an explanation?
> > > And this is the log:
> > > https://del.dog/wybokithyf
> > > ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)
> > 
> > 
> > Do simply `.update -alpha -pull -push` and `.restart -h` after update
> > I am sure you is not on latest, [see this](https://telegra.ph/file/7ab51b34c7a380c798691.jpg)
> 
> I waited for the deployment process, more than 3 minutes. then did -restart -h, but there was no response. in heroku has been successfully deployed, but the log displays a message like this
> 
> https://del.dog/vyfephalyc

Ahh, Add your bot In Log channel, and do Restart manually in heroku 🤘

**Comment by GlgApr** [comment]
> > > > some days the plugin unofficial command is gone, I check on heroku var, LOAD_UNOFFICIAL_PLUGINS = True.
> > > > I tried to change it to false then true but still not there. can you give an explanation?
> > > > And this is the log:
> > > > https://del.dog/wybokithyf
> > > > ![Screenshot_7](https://user-images.githubusercontent.com/11390074/89257449-6052fa80-d650-11ea-923a-c4b0c8bf5b3e.png)
> > > 
> > > 
> > > Do simply `.update -alpha -pull -push` and `.restart -h` after update
> > > I am sure you is not on latest, [see this](https://telegra.ph/file/7ab51b34c7a380c798691.jpg)
> > 
> > 
> > I waited for the deployment process, more than 3 minutes. then did -restart -h, but there was no response. in heroku has been successfully deployed, but the log displays a message like this
> > https://del.dog/vyfephalyc
> 
> Ahh, Add your bot In Log channel, and do Restart manually in heroku 🤘
thank you for your help, now it works hahaha

**Comment by GlgApr** [comment]
Thank you everyone who help me with this, now my bot comeback to me. Have good day, god bless u all!

**Comment by Harsh-br0** [comment]
M
