### ISSUE TITLE
small request

### ISSUE THREAD

**Issue by em108** [UsergeTeam/Userge#13]
Could there be an option added whereby one can download files from telegram or from links and gets automatically uploaded to Google drive or telegram respectively depending on the flags.

Say the new ytdl to telegram improvement with a flag `-t` was very handy and I was wondering if a flag `-g` for downloads module could be added such that one can automatically upload downloaded files to Google drive. 

It would then be` ".download -g <your reply to files in telegram>"` where `-g` is the suggestion for the flag.

Or say one wants to download from links and automatically upload to telegram;
`".download -t <your url>"`

It's currently possible if one uses the available commands in the gdrive module but this too might greatly simply the process.

Much thanks for the great development.

**Comment by rking32** [comment]
> It would then be` ".download -g <your reply to files in telegram>"` where `-g` is the suggestion for the flag.
did you try .gup <your reply to files in telegram> ?
> Or say one wants to download from links and automatically upload to telegram;
> `".download -t <your url>"`
use .upload <your url>

is it not simple ?

**Comment by em108** [comment]
Thank you so much for responding. I don't know why I hadn't tried it out but it's simple too and it's actually much simpler than what I had suggested earlier.

I just tried it out and it works. Thanks :)
