### ISSUE TITLE
Smart Copy 

### ISSUE THREAD

**Issue by theRay1s** [UsergeTeam/Userge#131]
Is it possible if we  Copy file ( .gcopy ) from TD OR  gdrive 
If that file already exist in destination bot don't copy it 

When we copy folder to folder in different td it will not copy same name n size files over n over again.

I know this feature is there when we syncing or copy via rclone

**Comment by lacyboi** [comment]
yeah then use rclone tht is way more dedicated for all these purpose.. dont expect everything from a userbot.🤡

**Comment by rking32** [comment]
it may lead to hit `user rate limits` instantly as @LikerPlayer mentioned #110
