### ISSUE TITLE
Some Issue

### ISSUE THREAD

**Issue by NEOIR** [UsergeTeam/Userge#134]
Hi, I Have a Some Issue:

1. I Create a Database in MongoDB, Blow URL is True ?
mongodb+srv://8321205:<@8321205!>@icluster.vpsl9.mongodb.net/<tirana>?retryWrites=true&w=majority

2. After Get HU_STRING_SESSION and add it to Config Var after Deploy Get Blow Errors
![image](https://user-images.githubusercontent.com/53754407/91540891-b570ec00-e930-11ea-913c-f5f2bad8ee8d.png)

3. What is Command of Bot?, When I Send Start Command in Bot not any Message in Bot

Thanks for This Repo.

**Comment by Krishna-Singhal** [comment]
Only your Error in DATABASE_URI

send url in OT group, will send correct url

**Comment by NEOIR** [comment]
my Database Url is : 

mongodb+srv://8321205:<@8321205!>@icluster.vpsl9.mongodb.net/<tirana>?retryWrites=true&w=majority

**Comment by Krishna-Singhal** [comment]
> my Database Url is :
> 
> mongodb+srv://8321205:<@8321205!>@icluster.vpsl9.mongodb.net/?retryWrites=true&w=majority
> 
> and Give this Url from Mongodb Connect Url:
> 
> ![image](https://user-images.githubusercontent.com/53754407/91545252-15b65c80-e936-11ea-9d9c-5ec9a3c87ccf.png)

send Password

**Comment by Krishna-Singhal** [comment]
or don't use any special characters in password

**Comment by NEOIR** [comment]
Hi

Database Problem Solved and Now Connected to Database.

1. Userge in Idling and Not Change Status, See Heroku Logs Blow Picture ( If You Want Send Full Logs )
![image](https://user-images.githubusercontent.com/53754407/91562907-35a84900-e953-11ea-80b2-ff40ddc1b6db.png)

2. in Database at MongoDB.com not Created any Collection ( samsam Collection Created by Me in First Database Creation )
![image](https://user-images.githubusercontent.com/53754407/91563044-7607c700-e953-11ea-87e1-8352526ea9d4.png)

3. Bot isnt any Response to Command /start ( bot Token and Owner Id adn Channel Id Set in Heroku )
![image](https://user-images.githubusercontent.com/53754407/91563234-c848e800-e953-11ea-88fd-927f2d86e86d.png)


Thanks for Help.

**Comment by Krishna-Singhal** [comment]
I can't send any abuse here, your problem solved and Userge Idling.
close Issue and talk in group 😗

**Comment by NEOIR** [comment]
Ok, Please send me Group Link

**Comment by Krishna-Singhal** [comment]
https://t.me/UserGeOT

you can close this issue also.

**Comment by NEOIR** [comment]
I'm Joind to group with link 
But I can't access to write in group .

**Comment by Krishna-Singhal** [comment]
> I'm Joind to group with link
> But I can't access to write in group .

What 🤔

**Comment by NEOIR** [comment]
@NEOIR

**Comment by rking32** [comment]
> Hi
> 
> Database Problem Solved and Now Connected to Database.
> 
>     1. Userge in Idling and Not Change Status, See Heroku Logs Blow Picture ( If You Want Send Full Logs )
>        ![image](https://user-images.githubusercontent.com/53754407/91562907-35a84900-e953-11ea-80b2-ff40ddc1b6db.png)
> 
>     2. in Database at MongoDB.com not Created any Collection ( samsam Collection Created by Me in First Database Creation )
>        ![image](https://user-images.githubusercontent.com/53754407/91563044-7607c700-e953-11ea-87e1-8352526ea9d4.png)
> 
>     3. Bot isnt any Response to Command /start ( bot Token and Owner Id adn Channel Id Set in Heroku )
>        ![image](https://user-images.githubusercontent.com/53754407/91563234-c848e800-e953-11ea-88fd-927f2d86e86d.png)
> 
> 
> Thanks for Help.

try `.ping`

**Comment by NEOIR** [comment]
Can i Send Message to Direct in Telegram for Issues ?

![image](https://user-images.githubusercontent.com/53754407/91594597-6601de80-e977-11ea-9d63-03560e7ec76c.png)

**Comment by NEOIR** [comment]
> > Hi
> > Database Problem Solved and Now Connected to Database.
> > ```
> > 1. Userge in Idling and Not Change Status, See Heroku Logs Blow Picture ( If You Want Send Full Logs )
> >    ![image](https://user-images.githubusercontent.com/53754407/91562907-35a84900-e953-11ea-80b2-ff40ddc1b6db.png)
> > 
> > 2. in Database at MongoDB.com not Created any Collection ( samsam Collection Created by Me in First Database Creation )
> >    ![image](https://user-images.githubusercontent.com/53754407/91563044-7607c700-e953-11ea-87e1-8352526ea9d4.png)
> > 
> > 3. Bot isnt any Response to Command /start ( bot Token and Owner Id adn Channel Id Set in Heroku )
> >    ![image](https://user-images.githubusercontent.com/53754407/91563234-c848e800-e953-11ea-88fd-927f2d86e86d.png)
> > ```
> > 
> > 
> > Thanks for Help.
> 
> try `.ping`

.Ping Command Response is;
157.899 ms

Whats Other Command and Usage ?

**Comment by rking32** [comment]
> > > Hi
> > > Database Problem Solved and Now Connected to Database.
> > > ```
> > > 1. Userge in Idling and Not Change Status, See Heroku Logs Blow Picture ( If You Want Send Full Logs )
> > >    ![image](https://user-images.githubusercontent.com/53754407/91562907-35a84900-e953-11ea-80b2-ff40ddc1b6db.png)
> > > 
> > > 2. in Database at MongoDB.com not Created any Collection ( samsam Collection Created by Me in First Database Creation )
> > >    ![image](https://user-images.githubusercontent.com/53754407/91563044-7607c700-e953-11ea-87e1-8352526ea9d4.png)
> > > 
> > > 3. Bot isnt any Response to Command /start ( bot Token and Owner Id adn Channel Id Set in Heroku )
> > >    ![image](https://user-images.githubusercontent.com/53754407/91563234-c848e800-e953-11ea-88fd-927f2d86e86d.png)
> > > ```
> > > 
> > > 
> > > Thanks for Help.
> > 
> > 
> > try `.ping`
> 
> .Ping Command Response is;
> 157.899 ms
> 
> Whats Other Command and Usage ?

try `.help`. you will learn. 
also closing this cuz this is a question
