### ISSUE TITLE
Run The user bot from pythonanywhere...

### ISSUE THREAD

**Issue by moshe-coh** [UsergeTeam/Userge#155]
i cannot run the bash from pythonanywhere.
I get an error that needs Python 3 and Python 3 is already installed. What should I do?
![image](https://user-images.githubusercontent.com/62907797/93365683-c5565e80-f852-11ea-98f7-713bfca47218.png)

**Comment by rking32** [comment]
try by installing python3.8 `sudo apt install python3.8` and this is not the place to ask questions.
join [here](https://t.me/usergeot) to ask questions

**Comment by Harsh-br0** [comment]
> I get an error that needs Python 3

Bruh , its version sensitive
you need to get version above 3.8 as mentioned
