### ISSUE TITLE
Usergebot

### ISSUE THREAD

**Issue by thelonewolf2** [UsergeTeam/Userge#165]

**Comment by ravana69** [comment]
Dil ka dariya beh hi gaya
Ishq ibadat ban hi gaya
Khud ko mujhe tu sonp de
Meri zaroorat tu ban gaya

Baat dil ki nazron ne ki
Sach keh raha, teri kasam
Tere bin ab na lenge ik bhi dam
Tujhe kitna chahne lage hum
Tere bin ab na lenge ik bhi dam
Tujhe kitna chahne lage hum
Tere sath ho jayenge khatam
Tujhe kitna chahne lage hum

Baat dil ki nazron ne ki
Sach keh raha, teri kasam
Tere bin ab na lenge ik bhi dam
Tujhe kitna chahne lage hum
Tere sath ho jayenge khatam
Tujhe kitna chahne lage hum
Tujhe kitna chahne lage hum

Iss jagah aa gayi chahatein ab meri
Chheen lunga tumhe saari duniya se hi
Tere ishq pe haan, haq mera hi toh hai
Keh diya hai ye maine mere Rab se bhi
Jis raste tu na mile
Us pe ho mere kadam

Tere bin ab na lenge ik bhi dam
Tujhe kitna chahne lage hum
Tere sath ho jayenge khatam
Tujhe kitna chahne lage hum
Tujhe kitna chahne lage hum
Oh… Oo… Oh…
Tujhe kitna chahne lage hum

**Comment by ravana69** [comment]
a

**Comment by ravana69** [comment]
b

**Comment by ravana69** [comment]
c

**Comment by ravana69** [comment]
d

**Comment by ravana69** [comment]
e

**Comment by ravana69** [comment]
f

**Comment by ravana69** [comment]
g

**Comment by ravana69** [comment]
h

**Comment by ravana69** [comment]
i

**Comment by ravana69** [comment]
j

**Comment by ravana69** [comment]
k

**Comment by ravana69** [comment]
l

**Comment by ravana69** [comment]
m

**Comment by ravana69** [comment]
n

**Comment by ravana69** [comment]
o

**Comment by ravana69** [comment]
p

**Comment by ravana69** [comment]
q

**Comment by ravana69** [comment]
r

**Comment by ravana69** [comment]
s

**Comment by ravana69** [comment]
t

**Comment by ravana69** [comment]
u

**Comment by ravana69** [comment]
v

**Comment by ravana69** [comment]
w

**Comment by ravana69** [comment]
x

**Comment by ravana69** [comment]
y

**Comment by ravana69** [comment]
z

**Comment by rking32** [comment]
@thelonewolf2 next time add proper `title` and `description`
