### ISSUE TITLE
Heroku Postgres instead of MongoDB

### ISSUE THREAD

**Issue by pseudokawaii** [UsergeTeam/Userge#167]
Can i use Heroku Postgres DB URL instead of MongoDB URL?

**Comment by Harsh-br0** [comment]
> Can i use Heroku Postgres DB URL instead of MongoDB URL?

Can you use soap in your toothbrush?

Question is same as that

**Comment by rking32** [comment]
> Can i use Heroku Postgres DB URL instead of MongoDB URL?

can't, they are totally different.
