### ISSUE TITLE
Add UDS (Unlimited Drive Storage) plugin for Userge.

### ISSUE THREAD

**Issue by pseudokawaii** [UsergeTeam/Userge#178]
It would be great if you can add https://github.com/stewartmcgown/uds as a plugin. can you do that?

**Comment by rking32** [comment]
what is the use of that ?

**Comment by pseudokawaii** [comment]
@rking32 why don't you read the README page? that's better than my explanation.

**Comment by rking32** [comment]
sorry, i don't like abusing free services :(

**Comment by Harsh-br0** [comment]
> It would be great if you can add https://github.com/stewartmcgown/uds as a plugin. can you do that?

Do u know what it does actually?

**Comment by pseudokawaii** [comment]
> > It would be great if you can add https://github.com/stewartmcgown/uds as a plugin. can you do that?
> 
> Do u know what it does actually?

It basically uses base64 encoding to convert any type of file to google docs format. since google docs doesn't require any space on your drive no matter how many documents you create and save, one can store unlimited amount of data on gdrive using this tool.

**Comment by pseudokawaii** [comment]
> sorry, i don't like abusing free services :(

What kind of abuse?? Google didn't request anyone to not use their free services to their full potentials, did they?

Google itself enabled the feature of Google Docs which is "not using any drive resource" then does it break any of Google's ToS if someone finds a way to use that feature like this? if not, then how's it an abuse of their free service?
