### ISSUE TITLE
Rename support in Gdrive module

### ISSUE THREAD

**Issue by pratik2596** [UsergeTeam/Userge#19]
Add Rename features in gdrive module wherever it's possible

**Comment by rking32** [comment]
to gup or gdown ?

**Comment by uaudith** [comment]
Or rename already existing files in gdrive ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pratik2596** [comment]
No rename isn't there right now, Rename can be added in gup so when uploading a file from tg to gdrive we can specify new name & same process can be added when uploading file from server to gdrive

**Comment by pratik2596** [comment]
Further you can add in gcopy & gmove also

**Comment by rking32** [comment]
@pratik2596 added rename support to `.gup` when uploading by path, link and replying to tg file.

**Comment by pratik2596** [comment]
Thank you ✌️
