### ISSUE TITLE
It is very slow it takes around 5 minutes to react

### ISSUE THREAD

**Issue by Gautampro1834** [UsergeTeam/Userge#194]

**Comment by Krishna-Singhal** [comment]
what slow ?

**Comment by Gautampro1834** [comment]
It takes much time to react on commands

**Comment by Harsh-br0** [comment]
> It takes much time to react on commands

Bruh , its not an issue , even u didn't specified which type of commands

**Comment by Harsh-br0** [comment]
> It takes much time to react on commands

Bruh , its not an issue , even u didn't specified which type of commands

**Comment by Gautampro1834** [comment]
Every command bro
Its take more than 5 minutes to execute a command

**Comment by rking32** [comment]
its not an issue of Userge. depend on your server and telegram response time. so closing ...
