### ISSUE TITLE
Maintain aspect ratio while uploading as video

### ISSUE THREAD

**Issue by newaccforhc** [UsergeTeam/Userge#195]
When a video is uploaded using `.upload` command, the aspect ratio is changed to 1:1 (at least on iOS device)
Same happens when used `.ytdl -t` command as well.

**Comment by newaccforhc** [comment]
Aspect ratio using userge:
![Uploading 99497385...]
Original aspect ratio (using a different bot):
![Uploading 99497427...]

**Comment by Harsh-br0** [comment]
I suggest you to learn markdown first
