### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cvatricks** [UsergeTeam/Userge#197]
Please add dyno on command via bot.

Eg.. : if dyno killed by die cmd, after /start cmd to Heroku bot dyno should on.

It will be more useful to save dyno.

**Comment by Krishna-Singhal** [comment]
#Shortage of Brain.

**Comment by rking32** [comment]
#invalid

> Please add dyno on command via bot.
> 
> Eg.. : if dyno killed by die cmd, after /start cmd to Heroku bot dyno should on.
> 
> It will be more useful to save dyno.

we can't. because bot is offline and how it can be ?
anyway you can use a separate bot to do this

**Comment by Harsh-br0** [comment]
> Please add dyno on command via bot.
> 
> Eg.. : if dyno killed by die cmd, after /start cmd to Heroku bot dyno should on.
> 
> It will be more useful to save dyno.

Bruh , keep ur logic and use [HK_Heroku_Bot](https://t.me/hk_heroku_bot) , it has scheduled dyno option
