### ISSUE TITLE
Humble request

### ISSUE THREAD

**Issue by j1shnu** [UsergeTeam/Userge#20]
1. Folder creating option for gdrive.
`.gmkdir  <folder name>`
2. Getting size of particular folder using link or id.
`.gsize <dir id> | <dir link> `

**Comment by rking32** [comment]
> 2. Getting size of particular folder using link or id.

check .gget also 😊

**Comment by j1shnu** [comment]
.gget only shows file size. I mean folder size

**Comment by rking32** [comment]
added `.gmake` command to make folders in gdrive parent.

check it out

**Comment by j1shnu** [comment]
Thanks buddy, just updated and checked it. Working perfectly. Great work!!!!

**Comment by rking32** [comment]
https://github.com/UsergeTeam/Userge/issues/131#issuecomment-678069323
