### ISSUE TITLE
add feature to disable userbot completly from specific chats

### ISSUE THREAD

**Issue by rking32** [UsergeTeam/Userge#213]
_summarized idea_

**commands**
* `dishere [chat username or id]` - argument optional. if user just send `.dishere`, should add current chat to disabled_chats 
* `enahere [-all] [chat username or id]` - argument required and flag optional. because we can't execute commands in disabled chats. if `.enahere [chat]` triggered, should remove that from disabled_chats. if `.enahere -all` triggered, should clear disabled_chats.

**process**
we can check chat_id for all incoming updates by adding like
```python
if r_m.chat and r_m.chat.id in Config.DISABLED_CHATS:
    return
```
before this line
https://github.com/UsergeTeam/Userge/blob/ab37c970ecc4cc83526ef0ec0a6341434915689f/userge/core/methods/decorators/raw_decorator.py#L238

_comment your ideas_

**Comment by Phyco-Ninja** [comment]
Why not add

```python
filters_ = filters_ & ~filters.chat(Config.DISABLED_CHATS) & (outgoing_flt | incoming_flt)
```
  [here](https://github.com/UsergeTeam/Userge/blob/alpha/userge/core/types/raw/command.py#L69)

**Comment by rking32** [comment]
> Why not add
> 
> ```python
> filters_ = filters_ & ~filters.chat(Config.DISABLED_CHATS) & (outgoing_flt | incoming_flt)
> ```
> 
> [here](https://github.com/UsergeTeam/Userge/blob/alpha/userge/core/types/raw/command.py#L69)

wow nice, but what about other incoming updates (without commands) like filters, ...

**Comment by Phyco-Ninja** [comment]
> wow nice, but what about other incoming updates (without commands) like filters (`on_filters`), ...

Then add it [here](https://github.com/UsergeTeam/Userge/blob/alpha/userge/core/types/raw/filter.py#L111)
