### ISSUE TITLE
Is the fork supported by official?

### ISSUE THREAD

**Issue by TomyPrs** [UsergeTeam/Userge#216]
This will make autopull official to fork #93 

The question is whether the official will always support it and whatever the changes?

Also someone asking too https://t.me/usergeot/655273

**Comment by rking32** [comment]
it will, but user should be able to resolve any conflicting issues if there exists

**Comment by TomyPrs** [comment]
Means the rules  he / she Gotta understand what he's doing and get to know git properly?

Oke got it  thanks for answer , and support 👍🏻
