### ISSUE TITLE
Add video trim & conversion 

### ISSUE THREAD

**Issue by pratik2596** [UsergeTeam/Userge#22]
Add video trim & conversion support, if possible use : https://github.com/cloudconvert/cloudconvert-python/blob/master/README.md

**Comment by innowebka** [comment]
i want this feature too... ffmpeg not works well and not accurate.
i need 20 minute segments of 4 hour video but it not works well.
or is there any solution ?

**Comment by rowdy-hero** [comment]
I also needs this video trimmer 😗😗

**Comment by theRay1s** [comment]
@innowebka use ffmpeg commands with 

Ex. 
.exec ffmpeg -i input.mp4 -ss 00:00:50.0 -codec copy -t 20 output.mp4

everything will work
