### ISSUE TITLE
Feature Request: Add wildcard asterisk (*)  support for upload command

### ISSUE THREAD

**Issue by alenpaul2001** [UsergeTeam/Userge#237]
### Wildcards will ease multiple file uploading. An example of such a scenario is described below :
------
#### Suppose I have a directory full of image files: 

```
README.md
requirements.txt
resources
run
runtime.txt
Screenshot_20201017-203855.png
Screenshot_20201017-203902.png
Screenshot_20201017-203908.png
Screenshot_20201017-203914.png
Screenshot_20201017-203919.png
Screenshot_20201017-203925.png
Screenshot_20201017-203933.png
Screenshot_20201017-203938.png
Screenshot_20201017-203945.png
Screenshot_20201017-203951.png
Screenshot_20201017-203957.png
Screenshot_20201017-204002.png
Screenshot_20201017-204013.png
Screenshot_20201017-204019.png
Screenshot_20201017-204030.png
```

Using the command ```.upload *.png``` should upload all png files to telegram.

**Comment by Harsh-br0** [comment]
Thats good @alenpaul2001  , but if u have a dir of images , then u just need to use `.upload {path_to_dir}`

**Comment by rking32** [comment]
closed by https://github.com/UsergeTeam/Userge/commit/b6d4878c51a25b566c74e217731f3793af7ea01a
