### ISSUE TITLE
optional progress icon

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge#24]
![resim](https://user-images.githubusercontent.com/63008918/82104806-fb5ac900-9720-11ea-9c13-839a0378e7b4.png)

at download / upload progress, we want to change this progress str.
defaultly:
completed: █ uncompleted: ░
an example: 
completed: ● uncompleted: ○

i think, at heroku deploy, we can add what we want ;)
thank you

**Comment by Phyco-Ninja** [comment]
U want some like this one? https://github.com/SpEcHiDe/PublicLeech/commit/843f8b13cf0513e5e3daa51536be2b0a7a617142 🤔

It have ne env var for setting progress strings.

**Comment by qorcfotian** [comment]
@Phyco-Ninja yes.

**Comment by rking32** [comment]
@qorcfotian now you can change progress string by setting FINISHED_PROGRESS_STR and UNFINISHED_PROGRESS_STR vars. Thanks @Phyco-Ninja

**Comment by qorcfotian** [comment]
@rking32 you're best :)
thank you man
