### ISSUE TITLE
Mora qualitas download

### ISSUE THREAD

**Issue by NoobPeoples** [UsergeTeam/Userge#243]
Please add this repo https://github.com/NoobPeoples/MQ-DL-Reborn

**Comment by otakuashwin** [comment]
please be clear with your issue and with your language

**Comment by pr13260** [comment]
Why don't create a fork for yourself
Most people don't even know about this site 
If you want it's support why don't you try to fork and upload file or add files using terminal provided
Bash Terminal would be of great help here
