### ISSUE TITLE
Additional Features for Notes and Unload

### ISSUE THREAD

**Issue by Phyco-Ninja** [UsergeTeam/Userge#25]
Hello UsergeTeam, 

I would like to suggest some additional features for like Bool switch for Notes and Command Disable. 

~Bool Switch:
In Notes.py line 46 there is a filter_me bool option, it would be better if u make a command which could switch between bool of filter_me as per user's reference. 

~Commands Disable:
This is a highly recommended addition, coz there are some commands like Kek, Lol, etc which trigger automatically. Mostly they are triggered accidentally,,, can u make something like commands disable like Emilia Bot :( so that it can be enabled or disabled anytime. 

•~Userge #OT Chat Reference »
•Notes Bool Switch-
1. https://t.me/usergeot/72924

•Disable Commands-
1. https://t.me/usergeot/72829
2. https://t.me/usergeot/72845
3. https://t.me/usergeot/72848

Hope You all will add these soon :)
Thank You

**Comment by Phyco-Ninja** [comment]
Loll 🤣 No Replies,, Even my gf could have replied faster 😛😛 (kidding)

**Comment by rameshchatarji** [comment]
Halo Amigos

**Comment by uaudith** [comment]
@Phyco-Ninja Can you do a PR

**Comment by Phyco-Ninja** [comment]
@uaudith PR for this i dunno sar 😅😅 if i knew how to make it, i would have tried to make it. :(  #New To Pyro

**Comment by rking32** [comment]
@Phyco-Ninja added

> ~Commands Disable:

but

> ~Bool Switch:

not yet 😁

**Comment by Phyco-Ninja** [comment]
Okay! Command disable will work for now 😛

**Comment by Harsh-br0** [comment]
> Loll  No Replies,, Even my gf could have replied faster  (kidding)

Ik ur gf just yesterday 😜😳

**Comment by Phyco-Ninja** [comment]
> > Loll  No Replies,, Even my gf could have replied faster  (kidding)
> 
> Ik ur gf just yesterday

👀
