### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pratik2596** [UsergeTeam/Userge#26]
Add a plugin for reverse image search

**Comment by rking32** [comment]
what is that 🤔 ? any references ?

**Comment by Phyco-Ninja** [comment]
@rking32 maybe he's asking for google reverse search,, like the one in uniborg https://github.com/SpEcHiDe/UniBorg/blob/master/stdplugins/google.py 🤔

**Comment by pratik2596** [comment]
Yup, i asking for that only

**Comment by rushiranpise** [comment]
Yandex one is more accurate https://yandex.com/images/

**Comment by pratik2596** [comment]
https://github.com/Dark-Princ3/X-tra-Telegram/blob/master/userbot/plugins/images.py
In addition add this too direct image search using some name with showing result in some images

**Comment by HyperNB** [comment]
How it's enhancement when it's not even in userge🤔

**Comment by rking32** [comment]
added to unofficial plugins

https://github.com/UsergeTeam/Userge-Plugins/pull/21
