### ISSUE TITLE
Userge Not Starting

### ISSUE THREAD

**Issue by Gowtham2003** [UsergeTeam/Userge#286]
I Followed Instructions and Deployed in Aws Server using "Docker Method"

I even Showed Starting ... initializing and things like that 

But later shows Exiting Userge 

docker compose log 

####  Starting Userge  #####  !>>>
userge_1  | Traceback (most recent call last):
userge_1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
userge_1  |     return _run_code(code, main_globals, None,
userge_1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
userge_1  |     exec(code, run_globals)
userge_1  |   File "/app/userge/__main__.py", line 14, in <module>
userge_1  |     userge.begin()
userge_1  |   File "/app/userge/core/client.py", line 196, in begin
userge_1  |     self.loop.run_until_complete(self.start())
userge_1  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
userge_1  |     return future.result()
userge_1  |   File "/app/userge/core/client.py", line 153, in start
userge_1  |     await super().start()
userge_1  |   File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
userge_1  |     is_authorized = await self.connect()
userge_1  |   File "/usr/local/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
userge_1  |     await self.load_session()
userge_1  |   File "/usr/local/lib/python3.8/site-packages/pyrogram/client.py", line 668, in load_session
userge_1  |     await self.storage.open()
userge_1  |   File "/usr/local/lib/python3.8/site-packages/pyrogram/storage/memory_storage.py", line 38, in open
userge_1  |     dc_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
userge_1  | struct.error: unpack requires a buffer of 263 bytes
userge_1  | [16-Mar-21 08:53:42 - INFO] - init - Exiting Userge ...
userge_userge_1 exited with code 0

**Comment by Phyco-Ninja** [comment]
where did u get `HU_STRING_SESSION`?

**Comment by Gowtham2003** [comment]
I think It's Telethon String , i recreated using Pyrogram and it's working 

Thanks
