### ISSUE TITLE
Add thumbnail permanent or atleast 5 to 6 hours please

### ISSUE THREAD

**Issue by sunilroy007** [UsergeTeam/Userge#296]
hello sir can you update thumbnail option to make thumbnail saved for atleast 5 to 6 hours, if permanent thumbnail support is not gonna available. i am using latest version and it reseting after every upload....

please make this request

**Comment by rking32** [comment]
isn't it permanent ?

**Comment by sunilroy007** [comment]
> isn't it permanent ?

no sir,  it resets i need to save thumbnail using !sthumb after every 1 video upload....  you can cross check it. 

please make it atleast 5 to 6 hours or permanent

**Comment by TomyPrs** [comment]
> > isn't it permanent ?
> 
> no sir, it resets i need to save thumbnail using !sthumb after every 1 video upload.... you can cross check it.
> 
> please make it atleast 5 to 6 hours or permanent

Hey bro . Custom Thumbnail now already Permanent.
If you still think thats are mess, you can join t.me/usergeot
And let's us know, which issue you have :)

**Comment by sunilroy007** [comment]
> > > isn't it permanent ?
> > 
> > 
> > no sir, it resets i need to save thumbnail using !sthumb after every 1 video upload.... you can cross check it.
> > please make it atleast 5 to 6 hours or permanent
> 
> Hey bro . Custom Thumbnail now already Permanent.
> If you still think thats are mess, you can join t.me/usergeot
> And let's us know, which issue you have :)

yes bro now its permanent. when i opened the issue its not.....

 maybe they changed in recent update. 

Thanks my issue solved

**Comment by rking32** [comment]
@sunilroy007 nice, so you can close this issue :)

**Comment by sunilroy007** [comment]
> @sunilroy007 nice, so you can close this issue :)

ok bro

**Comment by sunilroy007** [comment]
> @sunilroy007 nice, so you can close this issue :)

ok bro
