### ISSUE TITLE
add a split function (best 7z)

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge#30]
I have 7 GB file on heroku, I want to upload this file to telegram with multiple partz (example 7z.001... or rar.001...) 
exactly how to do split parts with userge?
any exec command or something?
(I tried with 7z but didn't work)

maybe a 7z split function will be ok. (with a size)
example:

`.pack7z -s 1400 abc.zip`
this command will split the abc.zip (example 5 gb) to 4 files:
```
abc.zip.001
abc.zip.002
abc.zip.003
abc.zip.004
```

and maybe a directory flay is useful. example:
`.pack7z -s 1400 -d abcfolder abc.zip`
this command will split the abc.zip (example 2 gb) to 2 files:
```
abcfolder/abc.zip.001
abcfolder/abc.zip.002
```
and maybe this py helps: 
https://github.com/SpEcHiDe/PublicLeech/blob/master/tobrot/helper_funcs/split_large_files.py

thank you :)

**Comment by rking32** [comment]
simply use `.split [file_size] [path]`. more info `.help split`

**Comment by qorcfotian** [comment]
sorry i didnt see that command. thank you :)
