### ISSUE TITLE
Failed deploying on railway.app

### ISSUE THREAD

**Issue by adnansidd99** [UsergeTeam/Userge#354]
![IMG_20210710_012521_548](https://user-images.githubusercontent.com/60623435/125126989-bb715500-e11d-11eb-994f-3c0f66f20d73.jpg)
Not able to deploy latest repo on railway.app site.

**Comment by dhruv-00** [comment]
Can you share build logs 🤔

**Comment by Krishna-Singhal** [comment]
can you share build logs ? 🤔🤔

**Comment by rking32** [comment]
try https://github.com/culturecloud/userge-docker
