### ISSUE TITLE
Not Found 404 error

### ISSUE THREAD

**Issue by kiam001** [UsergeTeam/Userge#363]
userge_1  | [11-Aug-21 11:43:07 - INFO] - init -        :: ERROR :: invalid request ! (caused by core.api._getResponse)                                                                                             userge_1  |     error_code : [404]                                                                        userge_1  |     description : "Not Found"                                                                 userge_1  | Exiting With SIGTERM (143) ...

**Comment by rking32** [comment]
your `LOG_CHANNEL_ID` and `BOT_TOKEN` correct ?

**Comment by rking32** [comment]
log channel id starts with `-100` ?

**Comment by rking32** [comment]
read and follow the documentation correctly http://theuserge.tech/deployment
