### ISSUE TITLE
Docker won´t build

### ISSUE THREAD

**Issue by sarah278** [UsergeTeam/Userge#377]
Userge won´t build from Dockerfile

First Part:
Package 'libgconf2-4' has no installation candidate --> change libgconf2-4 to libgconf-2-4
Package 'libnss3-1d' has no installation candidate --> change libnss3-1d to libnss3
 
Second Part:
...
Unpacking libc6:amd64 (2.31-17) over (2.28-10) ...
Setting up libc6:amd64 (2.31-17) ...
/usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
dpkg: error processing package libc6:amd64 (--configure):
 installed libc6:amd64 package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 libc6:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt -qq install -y --no-install-recommends     curl     git     gcc     g++     build-essential     gnupg2     unzip     wget     ffmpeg     libgconf-2-4     libnss3     libxss1     jq' returned a non-zero code: 100

For part 2 i haven´t a solution, but i´m looking in it...

**Comment by justTheKai** [comment]
Issue come from debian repo

**Comment by tomyprs** [comment]
> Userge won´t build from Dockerfile
> 
> First Part:
> Package 'libgconf2-4' has no installation candidate --> change libgconf2-4 to libgconf-2-4
> Package 'libnss3-1d' has no installation candidate --> change libnss3-1d to libnss3
> 
> Second Part:
> ...
> Unpacking libc6:amd64 (2.31-17) over (2.28-10) ...
> Setting up libc6:amd64 (2.31-17) ...
> /usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
> dpkg: error processing package libc6:amd64 (--configure):
> installed libc6:amd64 package post-installation script subprocess returned error exit status 127
> Errors were encountered while processing:
> libc6:amd64
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> The command '/bin/sh -c apt -qq install -y --no-install-recommends curl git gcc g++ build-essential gnupg2 unzip wget ffmpeg libgconf-2-4 libnss3 libxss1 jq' returned a non-zero code: 100
> 
> For part 2 i haven´t a solution, but i´m looking in it... Thanks for reporting issue

**Comment by rking32** [comment]
@justTheKai do you know how to fix ?

**Comment by sarah278** [comment]
@justTheKai this was the right hint...

**Comment by sarah278** [comment]
[Dockerfile.txt](https://github.com/UsergeTeam/Userge/files/7111806/Dockerfile.txt)

Build complete...

**Comment by sarah278** [comment]
Build complete...

Changes i made:

- python:3.9-slim-buster to python:3.9-slim-bullseye
- libgconf2-4 to libgconf-2-4
- libnss3-1d to libnss3
- 
[Dockerfile.txt](https://github.com/UsergeTeam/Userge/files/7111817/Dockerfile.txt)
