### ISSUE TITLE
bot broken after latest dockerfile update

### ISSUE THREAD

**Issue by sadequzv710** [UsergeTeam/Userge#382]
Hi.
i deployed the bot 3 days ago and everything was fine.but after the latest dockerfile update bot cant run and gets error at start : 

```
->- ->- ->- ->- ->- ->- ->- --- -<- -<- -<- -<- -<- -<- -<-

     ________            __  __               ______
    /_  __/ /_  ___     / / / /_______  _____/ ____/__
     / / / __ \/ _ \   / / / / ___/ _ \/ ___/ / __/ _ \
    / / / / / /  __/  / /_/ (__  )  __/ /  / /_/ /  __/
   /_/ /_/ /_/\___/   \____/____/\___/_/   \____/\___/


->- ->- ->- ->- ->- ->- ->- --- -<- -<- -<- -<- -<- -<- -<-
[15-Sep-21 11:41:03 - INFO] - init - Checking Bash Commands ...
[15-Sep-21 11:41:03 - INFO] - init - Checking Python Version ...
[15-Sep-21 11:41:03 - INFO] - init -    Found PYTHON - v3.9.7 ...
[15-Sep-21 11:41:03 - INFO] - init - Checking Config File ...
[15-Sep-21 11:41:03 - INFO] - init - Checking Required ENV Vars ...
[15-Sep-21 11:41:03 - INFO] - init -    :: ERROR :: Required API_ID var !
Exiting With SIGTERM (143) ...
->- ->- ->- ->- ->- ->- ->- --- -<- -<- -<- -<- -<- -<- -<-
```

then replaced the previous dockerfile and it runs again.

**Comment by rking32** [comment]
missing `API_ID` var. so filling that var properly will solve this case.

**Comment by Jigarvarma2005** [comment]
> missing `API_ID` var. so filling that var properly will solve this case.

Close it wen?

**Comment by sadequzv710** [comment]
> missing `API_ID` var. so filling that var properly will solve this case.

i have replaced api and all env.
just deployed now again. same problem.

the latest Dockerfile has problem. when i use the Dockerfile before september 12 it runs again.

thank you.

**Comment by rking32** [comment]
its weird

**Comment by Jigarvarma2005** [comment]
why this error comes🤔

**Comment by Jigarvarma2005** [comment]
why not adding 
```
COPY . .
```
[instead this](https://github.com/UsergeTeam/Userge/blob/8cca82972aac750e35b25c4b465036dd4374a951/Dockerfile#L48)

**Comment by tomyprs** [comment]
remove all "" in config.env better to use config.yml

**Comment by tomyprs** [comment]
> why not adding
> 
> ```
> COPY . .
> ```
> 
> [instead this](https://github.com/UsergeTeam/Userge/blob/8cca82972aac750e35b25c4b465036dd4374a951/Dockerfile#L48)

In few moments ago, it's causing update error

**Comment by Jigarvarma2005** [comment]
> > why not adding
> > ```
> > COPY . .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [instead this](https://github.com/UsergeTeam/Userge/blob/8cca82972aac750e35b25c4b465036dd4374a951/Dockerfile#L48)
> 
> In few moments ago, it's causing update error

ookh

**Comment by rking32** [comment]
Railway doesn't provide any free plans now r8? So reverting the Dockerfile. Thanks, @Jigarvarma2005 for your idea.
