### ISSUE TITLE
term command bug

### ISSUE THREAD

**Issue by SpEcHiDe** [UsergeTeam/Userge#393]
I think 🤔 [this](https://github.com/UsergeTeam/Userge/blob/alpha/userge/plugins/tools/executor.py#L386) is probably not killing the process properly.

Steps to Reproduce

1) download some big files (preferably slow link) using term `wget` command

2) while the download is less than 10% reply `cancel` command to the term process

Expected Result
The download should not proceed further

Actual Result
The download continues in the background, we can verify by doing term `ls -al` command and see the increased file size.

**Comment by rking32** [comment]
It worked for me with the latest alpha. Could you try to reproduce this with the latest alpha?
