### ISSUE TITLE
[ paste ] Paste as code support in pasting.ga

### ISSUE THREAD

**Issue by viperadnan-git** [UsergeTeam/Userge#397]
Hi, <https://pasting.ga> offers pasting as code as well as markdowns. It's great if we can configure the modes.

For pasting as code.
Set the `code` value to `True` in json.

**Comment by rking32** [comment]
As you can see here,
https://github.com/UsergeTeam/Userge/blob/2cc1e15e656cda29bd55ab588d23d83cb8d9861a/userge/plugins/utils/paste.py#L126-L127
it will do precisely this if `file_type` (extension) is there.

So try adding fake type like `.paste -p -fake [content_or_reply]` or replying `.paste -p` to a file which has an extention.

**Comment by viperadnan-git** [comment]
Nice 😊👍🏻
