### ISSUE TITLE
Filter Feature Please

### ISSUE THREAD

**Issue by DarkSuperMan09** [UsergeTeam/Userge#399]
Hello Devs, I think a Filter feature should be added in Userge. So If Someone Says something abusive so it can remove it and send a reply like Don't say abusive words. Or if someone sends a + icon, it will say Upvoted.
Just like the feature of MissRose_bot.
/filter + Upvoted
/filter Nudes Don't ask for nudes here, it's forbidden. 
Can you guys do it please?
Thanks!

**Comment by Harsh-br0** [comment]
Did you checked about it before opening issue?
I mean bot have .help to explore cmds then why guys need everything to be spoonfed

**Comment by DarkSuperMan09** [comment]
Thanks Harsh Bro.
But I'm sorry, I didn't explained it correctly. 

I was trying to say that the filter option should have been easy to use. 

If you have used missrose bots filter, then you can understand what I am asking for. 

Userge has filter feature too but it's very complicated. If it can be made easy and for all purpose use. It will be great, thanks for time.

**Comment by tomyprs** [comment]
> Thanks Harsh Bro.
> But I'm sorry, I didn't explained it correctly. 
> 
> I was trying to say that the filter option should have been easy to use. 
> 
> If you have used missrose bots filter, then you can understand what I am asking for. 
> 
> Userge has filter feature too but it's very complicated. If it can be made easy and for all purpose use. It will be great, thanks for time.

Can you explain `complicated` cases?

**Comment by Krishna-Singhal** [comment]
> Thanks Harsh Bro. But I'm sorry, I didn't explained it correctly.
> 
> I was trying to say that the filter option should have been easy to use.
> 
> If you have used missrose bots filter, then you can understand what I am asking for.
> 
> Userge has filter feature too but it's very complicated. If it can be made easy and for all purpose use. It will be great, thanks for time.

There is Nothing complicated in Userge.

Filters of Rose Bot is pretty same as Userge's filters., you just have to read help of filters then you are good to go.
