### ISSUE TITLE
send messages every X minutes

### ISSUE THREAD

**Issue by sadequzv710** [UsergeTeam/Userge#406]
hello and thanks for the amazing bot.

is there any way or plugin that can send some commands to bot every X minutes ?
i want to check some thing every 10 minutes on my server and want to send some messages to bot to run commands on server and send the result to telegram bot and a channel.
is this possible ?

thanks.

**Comment by Harsh-br0** [comment]
> is there any way or plugin that can send some commands to bot every X minutes ?

There's not a plugin but there's a way which is learn to do that by python , task scheduling knowledge ¯\_(ツ)_/¯

**Comment by Krishna-Singhal** [comment]
Hey @sadequzv710 , I hope @Harsh-br0 Answered your question. Closing with this comment.
