### ISSUE TITLE
request to update translate.py

### ISSUE THREAD

**Issue by SpEcHiDe** [UsergeTeam/Userge#408]
Please update https://github.com/UsergeTeam/Userge/blob/alpha/userge/plugins/utils/translate.py to support all types of text in Telegram Messages

**Comment by rking32** [comment]
Hi, what did you mean by all types of text?

**Comment by Navaneeth-Renjith-8282** [comment]
> Hi, what did you mean by all types of text?

@SpEcHiDe meant about all languages of text.

**Comment by Krishna-Singhal** [comment]
> Hi, what did you mean by all types of text?

I think he is talking about different and weird fonts on Telegram.

**Comment by SpEcHiDe** [comment]
> Hi, what did you mean by all types of text?

I meant like UserGe need to support different types of messages that can be sent in Telegram in the translate plugin 

Currently it only supports text and captions.

One Example: https://t.me/tginfo/3139
