### ISSUE TITLE
Can't use markdowns in notes!

### ISSUE THREAD

**Issue by NavaneethRenjith8282** [UsergeTeam/Userge#410]
# Markdowns not working in notes!
I've created a note using some markdowns. But, it is **not working** in notes.
I've checked the note again, it didn't shows markdowns.
Markdowns in Notes is already added in bots like [Rose Bot](https://t.me/MissRose_bot).
### Tip
Fixing this issue will help others to add **markdowns** to notes.

**Comment by Harsh-br0** [comment]
U dont need to have markdowns ig
Just format the message as you want

**Comment by Navaneeth-Renjith-8282** [comment]
> U dont need to have markdowns ig Just format the message as you want

I mean, I used the in-app formating.
But, it is also not working.

**Comment by Krishna-Singhal** [comment]
> > U dont need to have markdowns ig Just format the message as you want
> 
> I mean, I used the `in-app formating`. But, it is also not working. Then, how can I use in notes?

`in-app formatting` definitely won't work., just read help of notes.

**Comment by Navaneeth-Renjith-8282** [comment]
> > I mean, I used the `in-app formating`. But, it is also not working. Then, how can I use in notes?
> 
> `in-app formatting` definitely won't work., just read help of notes.

Ok. 
**Thanks for your help.** 😊

**Comment by Navaneeth-Renjith-8282** [comment]
> > I mean, I used the `in-app formating`. But, it is also not working. Then, how can I use in notes?
> 
> `in-app formatting` definitely won't work., just read help of notes.

But, it affects the usage of notes.
When some markdowns (e.g: **bold**) is used for a message in Telegram, it automatically changes to `in-app formatting`.
Due to this, I can't use markdowns like **bold** in notes.

**Comment by NavaneethRenjith8282** [comment]
##  No problem.
Really, now no problem with this issue.
Because @Harsh-br0 given me a tip for this in [**_Userge OffTopic_**](https://t.me/UsergeSpam) group.
![View message...](https://t.me/UserGeSpam/337486)

**Comment by Krishna-Singhal** [comment]
So closinf this issue now.
