### ISSUE TITLE
Not working in PM!

### ISSUE THREAD

**Issue by Navaneeth-Renjith-8282** [UsergeTeam/Userge#412]
# Userge is not working in PM!
I've checked some commands in Saved Messages. There, it is working.
It is also working in groups.
But, from now, I experience an issue with Userge in PM.
## Problem
Some commands of Userge is not working in someone's private messaging section. 
The commands or plugins including `notes` will work. But, nearly all types of commands/plugins are not working.
### Photos
I've checked the `.ping` command in bot, Saved Messages, and PM. But, in PM, not working.
The photo given here is an example.
![InShot_20211205_224030973](https://user-images.githubusercontent.com/93482811/144756338-214e9e22-4e9a-40b4-83bc-1624f9c4e468.jpg)

**Comment by rking32** [comment]
thanks for knowing us. it's fixed now.

**Comment by Navaneeth-Renjith-8282** [comment]
> thanks for knowing us. it's fixed now.

**Thanks!** ❤️
