### ISSUE TITLE
Add automated inline feature!

### ISSUE THREAD

**Issue by NavaneethRenjith8282** [UsergeTeam/Userge#421]
# Add automated inline!
Please add an automated inline facility in Userge. This will help others using bot mode.
Really, this feature is already added in [Ultroid](https://github.com/TeamUltroid/Ultroid) userbot.
## Why do I requested to add this?
Userge has so many plugins and features. But, there are some features that is not added in **Userge** but already added in other userbots, like [Ultroid](https://github.com/TeamUltroid/Ultroid). It includes this feature also.
So, I think Userge also want to add this feature. Because, it is a really, really good feature that I miss in Userge.
## Required commands that uses automated inline facility
There are some required commands that uses automated inline.
For example:
```
# Open inline Userge Main Menu:
.menu
# Then, deletes the command and opens
   Userge main menu through inline mode:
🖥️ **Userge Main Menu** 🖥️
```
Like this shown above.
Really, if you add this `{tr}menu` command in Userge, it will be helpful to others using Bot Mode. Then, they can type `.menu` in their chat to open **Userge Main Menu** through inline.
## For opening notes and filters through inline
This feature also good for using `notes` and `filters` through inline mode. 
Add a feature to use notes and filters in inline. Then, add automated inline to this inline notes and filters option.
```
# For example, I try to open a note:
#test
# Then, automatically opens the notes through inline:

via **@PMNava_bot**
📝 **Note**: `#test`

This note is for test.
```
```
# For example, I try to use a filter:
What is Userge?
# Filter opens through inline:

via **@PMNava_bot**
**About Userge**
**[Userge](https://github.com/UsergeTeam/Userge) is a powerful, _pluggable_ Telegram userbot written in Python using Pyrogram.
For more information, visit **Userge Docs**.
[Userge Docs][buttonurl:http://theuserge.tech]
```
Note: 
- [@PMNava_bot](https://t.me/PMNava_bot)  is an example here. Don't give like that.
- This feature won't work if the bot is added in the chat.

So, please add this automated inline to Userge userbot. It will helpful for so much people to use Userge.

**Regards,
[Navaneeth R](https://github.com/NavaneethRenjith8282)**

**Comment by tomyprs** [comment]
Inline notes, like userge X ?
