### ISSUE TITLE
how to split the video into segments ?

### ISSUE THREAD

**Issue by innowebka** [UsergeTeam/Userge#45]
i have 3 hour video and i need 20 minute segments so how to do that ?

**Comment by innowebka** [comment]
any tutorials ?

**Comment by pratik2596** [comment]
Use FFMPEGSAVE then FFMPEGTRIM

**Comment by rking32** [comment]
enable unofficial and use ff_mpeg

**Comment by innowebka** [comment]
how to enable ffmpeg ?

**Comment by rking32** [comment]
> how to enable ffmpeg ?

https://github.com/UsergeTeam/Userge/blob/557a0d53a43901a8bbd01b998328ce44c4e7596a/config.env.sample#L36
