### ISSUE TITLE
Feature Request: voice_call improvements

### ISSUE THREAD

**Issue by yshalsager** [UsergeTeam/Userge#468]
- Add the ability to stream from URLs and local files
It should be easy to add the ability to stream from URLs and local files to Telegram voice / video calls.
For URLs: https://github.com/pytgcalls/pytgcalls/blob/master/example/remote_piped_play/example_remote_piped.py#L18
For files: https://github.com/pytgcalls/pytgcalls/blob/master/example/calls_with_module/example_module.py#L20

- ~Add the ability to stream from YouTube directly without downloading the file~ Edit: Already exists.
https://github.com/pytgcalls/pytgcalls/blob/master/example/youtube_dl/youtube_dl_example.py

**Comment by Code-X-Mania** [comment]
maybe support direct download links too!

**Comment by yshalsager** [comment]
> maybe support direct download links too!

Direct download links = "URLs" I mentioned I believe :)

**Comment by subinps** [comment]
@yshalsager Have you checked the codes of the existing vc plugin?
The second one is the current implementation. We aren't downloading anything. just using stream url's from youtube to stream into vc.

**Comment by Krishna-Singhal** [comment]
> * Add the ability to stream from URLs and local files
>   It should be easy to add the ability to stream from URLs and local files to Telegram voice / video calls.
>   For URLs: https://github.com/pytgcalls/pytgcalls/blob/master/example/remote_piped_play/example_remote_piped.py#L18
>   For files: https://github.com/pytgcalls/pytgcalls/blob/master/example/calls_with_module/example_module.py#L20
> * Add the ability to stream from YouTube directly without downloading the file
>   https://github.com/pytgcalls/pytgcalls/blob/master/example/youtube_dl/youtube_dl_example.py

Only need to add first point, second point already there in vc plugin

**Comment by yshalsager** [comment]
> @yshalsager Have you checked the codes of the existing vc plugin? The second one is the current implementation. We aren't downloading anything, just using stream url's from youtube to stream into vc.

Ah yeah, I went through the file quickly but didn't read every line. You're right, sorry for that.
