### ISSUE TITLE
I want more security for environmental variables

### ISSUE THREAD

**Issue by jigarvarma2k20** [UsergeTeam/Userge#492]
Fix for this https://t.me/UserGeSpam/394593

**Comment by Krishna-Singhal** [comment]
> Fix for this https://t.me/UserGeSpam/394593

current security enough or need more ?

**Comment by jigarvarma2k20** [comment]
> > Fix for this https://t.me/UserGeSpam/394593
> 
> current security enough or need more ?

Need more

**Comment by Krishna-Singhal** [comment]
> Need more

https://github.com/UsergeTeam/Userge/blob/18bb3b9d1d563f22ff47e2b7179629779d8d30c1/userge/config.py#L20-L21
