### ISSUE TITLE
Docker Deployment Dead?

### ISSUE THREAD

**Issue by box-automation1** [UsergeTeam/Userge#495]
I wanted to deploy on my local vps today, followed the guide on the website, noticed that there's no dockerfile.
Dockerfile was removed from commit 3b1d6ae93d17e906944b955fe82ce6f41f49f644
Are there plans to bring it back?

**Comment by ZekXtreme** [comment]
https://github.com/UsergeTeam/Loader see here

**Comment by Krishna-Singhal** [comment]
> I wanted to deploy on my local vps today, followed the guide on the website, noticed that there's no dockerfile. Dockerfile was removed from commit [3b1d6ae](https://github.com/UsergeTeam/Userge/commit/3b1d6ae93d17e906944b955fe82ce6f41f49f644) Are there plans to bring it back?

Mostly things are changed after v1, seems you are not up to date with userge's new versions.
head over to [Loader](https://github.com/UsergeTeam/Loader) and see [deployment guide](https://t.me/UserGeSpam/378116) based on your os.

**Comment by Krishna-Singhal** [comment]
You can also contact in [support chat](https://telegram.me/usergespam), closing....
