### ISSUE TITLE
need a magnet link download plugin

### ISSUE THREAD

**Issue by cdfxscrq** [UsergeTeam/Userge#50]
hi  bro we need a magnet and torrent file download plugin !!!!

**Comment by rking32** [comment]
nope

**Comment by Harsh-br0** [comment]
> hi bro we need a magnet and torrent file download plugin !!!!

Heroku :- am i joke to you

**Comment by prono69** [comment]
Never

**Comment by prono69** [comment]
@cdfxscrq man... Are You Mad

_Sent from my Redmi Note 4 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Harsh-br0** [comment]
> @cdfxscrq man... Are You Mad
> 
> _Sent from my Redmi Note 4 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

Promoting fasthub libre 🌚
