### ISSUE TITLE
Google drive support

### ISSUE THREAD

**Issue by KelvinCrag** [UsergeTeam/Userge#500]
It appears that one of the key [features](http://theuserge.tech/#features) of userge "Google drive support" no longer work. Few weeks ago there was [reports](https://t.me/usergeot/805397) of credentials being forgotten when app goes idle or restarts.

Sadly now it has come to my notice that Google drive no longer work at all in userge, it doesn't recognize both `G_DRIVE_CLIENT_ID` and `G_DRIVE_CLIENT_SECRET` ENVIRONMENT VAR 

Thanks for your generous support all these while and I hope it gets fixed.

**Comment by Krishna-Singhal** [comment]
Seems it's a Bug, try restarting heroku dynos, It will work.

It is because, secured_str() delete env vars of gdrive and you are trying to use gdrive after doing restart. so plugin will not recognise vars since they are popped.
