### ISSUE TITLE
Fatal git error 

### ISSUE THREAD

**Issue by Akshaygit1** [UsergeTeam/Userge#51]
Hello
I'm unable to start bot using bash run.
Not using heroku followed steps mentioned in other method of README.md.
![Screenshot_20200609-002936748 (1)](https://user-images.githubusercontent.com/60196069/84069946-f966eb80-a9e8-11ea-8261-4f5d52936e37.jpg)
removing/commenting checking repo code from userge/config.py starts bot but .update command then gives same error too.

**Comment by rking32** [comment]
hmm :thinking:

**Comment by rking32** [comment]
@Akshaygit1 did you set upstream repo ?

**Comment by Akshaygit1** [comment]
> @Akshaygit1 did you set upstream repo ?

At 1st no, as it's optional var so i didn't bother to fill it 1st time. But later i tried setting it to https://github.com/UsergeTeam/Userge but still same error.

**Comment by behf** [comment]
I have the same issue, it seems the optional fields in the config.dev are not optional. I got an error for LOG_CHANNEL_ID too.

**Comment by behf** [comment]
this solved issue for me:
`git remote rm upstream`
`git remote add upstream 'https://github.com/UsergeTeam/Userge.git'`

**Comment by Akshaygit1** [comment]
> this solved issue for me:
> `git remote rm upstream`
> `git remote add upstream 'https://github.com/UsergeTeam/Userge.git'`

Thanks, worked for me too.
Closing this for now.
