### ISSUE TITLE
[integrate] deezloader (deezer downloader)

### ISSUE THREAD

**Issue by qorcfotian** [UsergeTeam/Userge#52]
may this link helps: https://github.com/SpEcHiDe/UniBorg/blob/master/stdplugins/deezload.py

**Comment by rking32** [comment]
already in userge-plugins repo. if you want enable unofficial support

https://github.com/UsergeTeam/Userge/blob/f8d64daa321a8d17c05a9e07c8a12bfefd72b1b1/config.env.sample#L36-L37

**Comment by Harsh-br0** [comment]
Hey 
That issue still opened after 30 mins 👀
