### ISSUE TITLE
(Enhancement) Purge plugin 

### ISSUE THREAD

**Issue by Akshaygit1** [UsergeTeam/Userge#57]
Wanted to suggest couple of improvements to current purge plugin.
1:- purge only in single/current chat where purge command is used. Currently purging deletes messages in other chat/groups too. Is this intended behaviour?
2:- purge x number of messags. This can be added as flag (.purge -n number_here)

**Comment by minato99-x** [comment]
I have the same issue too. Any fix found?

**Comment by rking32** [comment]
still not, will fix it soon

**Comment by Akshaygit1** [comment]
Thanks but now purge command doesn't work in private or in bot chat. @rking32 

> Sorry!, this command not supported in this chat type [private] !

> Sorry!, this command not supported in this chat type [bot] !

**Comment by rking32** [comment]
@Akshaygit1 yes
if you use purge in private it will delete messages in other chats too
maybe pyrogram reason 🤔

**Comment by Akshaygit1** [comment]
Ah okay :/ seems like pyrogram still new bcoz it works with telethon.

**Comment by rking32** [comment]
hmm :cry:
