### ISSUE TITLE
Command alias 

### ISSUE THREAD

**Issue by Akshaygit1** [UsergeTeam/Userge#60]
Want to request plugin for making alias of commands.
Imo it's very useful. 
Example. 
.alias .paste -n | .np
Currently to paste text on nekobin we need to use 
.paste -n text_here 
With alias we can shorten this drastically to. 
.np text_here
This is just one example to show how it's helpful.

**Comment by rking32** [comment]
hmm... seems a good idea :smiley:
will check this soon :+1:

**Comment by rking32** [comment]
sorry @Akshaygit1, i didn't realize that before.
this may lead to commands conflict issues. so closing this ...
