### ISSUE TITLE
Got an error during "bash genStr"

### ISSUE THREAD

**Issue by Nenokkadine** [UsergeTeam/Userge#61]
![image](https://user-images.githubusercontent.com/65813999/84599144-71bc2980-ae8d-11ea-9c9f-96ba81a5d240.png)
I gave the bot token as input and this happened

**Comment by Harsh-br0** [comment]
> ![image](https://user-images.githubusercontent.com/65813999/84599144-71bc2980-ae8d-11ea-9c9f-96ba81a5d240.png)
> I gave the bot token as input and this happened

Sir its true that bots cant send messages to other bots
Even users too👀

**Comment by Nenokkadine** [comment]
when i authorize my telegram i am getting the String to saved messages but i am unable to access the bot because i haven't given the Bot token anywhere How to access the bot

**Comment by death-angel-141** [comment]
Check ur bot in BotFather,there u will get ur bot token as well as the bot username

**Comment by pratik2596** [comment]
Copy the string you got in saved messages & paste that in Heroku vars in HU_STRING_SESSION

**Comment by Nenokkadine** [comment]
I copied it but my bot is not responding 🤷‍♂️

**Comment by Akshaygit1** [comment]
Afaik userge only works as userbot (selfbot) you can't use it as other bot.

**Comment by Nenokkadine** [comment]
[usergemine-logs-1592239029986.txt](https://github.com/UsergeTeam/Userge/files/4781658/usergemine-logs-1592239029986.txt)
Ok There are some errors occouring I Cant find them
attaching the logs here. TIA

**Comment by pratik2596** [comment]
@Nenokkadine There is some issue with database for futher clarification join https://t.me/usergeot
