### ISSUE TITLE
AFK private message 

### ISSUE THREAD

**Issue by Akshaygit1** [UsergeTeam/Userge#66]
Afk doesn't respond for private messages.
It works in basic/super groups but in private message no I'm afk right now message.
Nothing in logs too.

**Comment by Akshaygit1** [comment]
Also does afk message respond only once per user? Or is there some time logic too?

**Comment by Harsh-br0** [comment]
> Also does afk message respond only once per user? Or is there some time logic too?

Are you in usergeot?🤔

**Comment by rking32** [comment]
> Also does afk message respond only once per user? Or is there some time logic too?

it won't response for all messages. only for randomly selected messages

**Comment by Akshaygit1** [comment]
> > Also does afk message respond only once per user? Or is there some time logic too?
> 
> Are you in usergeot?

No 😐

> > Also does afk message respond only once per user? Or is there some time logic too?
> 
> it won't response for all messages. only for randomly selected messages

Ah okay. Hope soon it gets fixed in private message too :)

**Comment by rking32** [comment]
@Akshaygit1 AFK working fine in Private (just checked)
please check it again

**Comment by Akshaygit1** [comment]
> @Akshaygit1 AFK working fine in Private (just checked)
> please check it again

Weird it doesn't work for me. Nothing in logs too
https://del.dog/ihuxokiwus.txt
Exact steps i did. 
Restarted bot (.restart) set afk (.afk testing) now sent message to myself using alt but got no I'm afk right now message.

**Comment by rking32** [comment]
@Akshaygit1 don't use AFK yourself. it won't work anymore

try to PM your account with other account

**Comment by Akshaygit1** [comment]
> @Akshaygit1 don't use AFK yourself. it won't work anymore
> 
> try to PM your account with other account

Yes that's exactly what i did. After doing afk command i pmed myself using my alt account. But got no afk reply.
Btw I'm using alpha branch (not sure If that's relevant to this issue or not)

**Comment by theRay1s** [comment]
@Akshaygit1 afk is working perfect in both private  and group

**Comment by Akshaygit1** [comment]
I see that's weird, looks like I'm the only one facing this then. Any hints what might be the reason?

**Comment by rking32** [comment]
@Akshaygit1 have you enabled pmguard ?

**Comment by Akshaygit1** [comment]
> @Akshaygit1 have you enabled pmguard ?

No, i don't use pmpermit plugin.

**Comment by rking32** [comment]
hmm **noted**
