### ISSUE TITLE
#Feature 

### ISSUE THREAD

**Issue by spkal01** [UsergeTeam/Userge#71]
A nice feature  would be a custom block pm message command on pm guard

**Comment by rking32** [comment]
did you mean custom pm message ?

**Comment by spkal01** [comment]
No I mean when someone spams and the bot tells for example u were blocked and thats the thing I am referring on my above message .
Picture : 
![Screenshot_20200620-112511243~2](https://user-images.githubusercontent.com/65872023/85197336-0b019a80-b2e9-11ea-85bf-d3b0cab16157.jpg)
