### ISSUE TITLE
#Feauture 

### ISSUE THREAD

**Issue by spkal01** [UsergeTeam/Userge#72]
A cool feature would be an interactive auto pm message like this one used on XtratgBot repo : https://github.com/Dark-Princ3/X-tra-Telegram

Pictures 
![Screenshot_20200619-183733369](https://user-images.githubusercontent.com/65872023/85164592-42326600-b26d-11ea-825a-a96d46212a8d.jpg)
![Screenshot_20200619-183959734](https://user-images.githubusercontent.com/65872023/85164691-62622500-b26d-11ea-85c6-58d96312b121.jpg)

**Comment by rking32** [comment]
😂😂

**Comment by rking32** [comment]
this is useless. so closing this

**Comment by prono69** [comment]
Nice work 👌

**Comment by Harsh-br0** [comment]
> this is useless. so closing this

😶😶
