### ISSUE TITLE
.term command limit

### ISSUE THREAD

**Issue by temporhodes** [UsergeTeam/Userge#74]
hello.
i use .term alot.but thw bot can only run 4 at same time.when i run the 5th .term command it doesnt respond.
pls extend the number of .term commands simultaneously.

thanks.

**Comment by udaythefreelancer** [comment]
I think if the Dev increased the limit, the not might crash

**Comment by Harsh-br0** [comment]
> hello.
> i use .term alot.but thw bot can only run 4 at same time.when i run the 5th .term command it doesnt respond.
> pls extend the number of .term commands simultaneously.
> 
> thanks.

Increase workers 
Then try 🤔
[Check that line](https://github.com/UsergeTeam/Userge/blob/d515ba91b8a8e58a9f2fe0b0160a3e4f621d876d/config.env.sample#L43)
