### ISSUE TITLE
Giving error on bash run command

### ISSUE THREAD

**Issue by rahul-instinct** [UsergeTeam/Userge#77]
This is giving me error whenever i try to run this command "bash run"
Error- Userge can't be used in 'await' expression.
My python version is 3.8.3 and i am using Ubuntu
![20200622_065636](https://user-images.githubusercontent.com/57611684/85254124-31583f00-b47d-11ea-8441-0e73a5dc9c93.jpg)

**Comment by Harsh-br0** [comment]
> This is giving me error whenever i try to run this command "bash run"
> Error- Userge can't be used in 'await' expression.
> My python version is 3.8.3 and i am using Ubuntu
> ![20200622_065636](https://user-images.githubusercontent.com/57611684/85254124-31583f00-b47d-11ea-8441-0e73a5dc9c93.jpg)

get_messages without any gap in time interval giving this god level error😕

**Comment by rking32** [comment]
@rahul-instinct have you solved this ?

**Comment by rking32** [comment]
this can solve by `python3.8 -m pip install -U git+https://github.com/pyrogram/pyrogram.git@asyncio-dev`
