### ISSUE TITLE
file to thumbnail

### ISSUE THREAD

**Issue by jassmineren** [UsergeTeam/Userge#9]
as i wrote before bot may set thumbnail from **file**
when i try to reply a jpeg file with .sthumb it giving this message:
`reply to a photo to save custom thumbnail`

In short, this feature works with **images** but it should be for the **files**:
_example: blabla.png (as a file. not image)_

I hope I could explain. thank you for your interest :)

**Comment by rking32** [comment]
thanks, issue fixed now
