### ISSUE TITLE
See this and respond please

### ISSUE THREAD

**Issue by pboy192** [UsergeTeam/Userge#95]
Can u please add the gmute function in this.
Or if it is already added tell me how to use that.
-Thanks

**Comment by rking32** [comment]
what is `gmute`
any brief explain ?

**Comment by nischay03654** [comment]
> what is `gmute`
> any brief explain ?

Ahh it is like gban... Suppose you are admin in 10 groups and u gmuted a person which is also in those 10 groups... So whenever that person posts anything in those groups, the userbot will delete his message asap(need to be admin first) I saw this feature in many telegram userbkts like x-tra.  Please try to add this feature, it will really help us.. appreciate your work👏
-Thanks

**Comment by rking32** [comment]
will try, need help @Phyco-Ninja

**Comment by Phyco-Ninja** [comment]
> > what is `gmute`
> > any brief explain ?
> 
> Ahh it is like gban... Suppose you are admin in 10 groups and u gmuted a person which is also in those 10 groups... So whenever that person posts anything in those groups, the userbot will delete his message asap(need to be admin first) I saw this feature in many telegram userbots like x-tra. Please try to add this feature, it will really help us.. appreciate your work
> -Thanks

This can be done by:
1. Adding Incoming Filter to current gban Module. 
2. If user is not and admin in current common chats. Mute him directly. 
3. If user tends to be an admin delete his incoming messages (if you are not the creator or admin is not promoted by you)

**Comment by nischay03654** [comment]
> > > what is `gmute`
> > > any brief explain ?
> > 
> > 
> > Ahh it is like gban... Suppose you are admin in 10 groups and u gmuted a person which is also in those 10 groups... So whenever that person posts anything in those groups, the userbot will delete his message asap(need to be admin first) I saw this feature in many telegram userbots like x-tra. Please try to add this feature, it will really help us.. appreciate your work
> > -Thanks
> 
> This can be done by:
> 
> 1. Adding Incoming Filter to current gban Module.
> 2. If user is not and admin in current common chats. Mute him directly.
> 3. If user tends to be an admin delete his incoming messages (if you are not the creator or admin is not promoted by you)

But the problem is if you are an admin and mute a person in a chat, so any other admin can unmute him as u know but if we have delete message permission in that chat we can just delete every message he post... And this cannot be stopped by anyone unless or until your delete message permission is removed.

**Comment by Phyco-Ninja** [comment]
> > > > what is `gmute`
> > > > any brief explain ?
> > > 
> > > 
> > > Ahh it is like gban... Suppose you are admin in 10 groups and u gmuted a person which is also in those 10 groups... So whenever that person posts anything in those groups, the userbot will delete his message asap(need to be admin first) I saw this feature in many telegram userbots like x-tra. Please try to add this feature, it will really help us.. appreciate your work
> > > -Thanks
> > 
> > 
> > This can be done by:
> > 
> > 1. Adding Incoming Filter to current gban Module.
> > 2. If user is not and admin in current common chats. Mute him directly.
> > 3. If user tends to be an admin delete his incoming messages (if you are not the creator or admin is not promoted by you)
> 
> But the problem is if you are an admin and mute a person in a chat, so any other admin can unmute him as u know but if we have delete message permission in that chat we can just delete every message he post... And this cannot be stopped by anyone unless or until your delete message permission is removed.

Lelz if admin umutes user. As soon as userbot detects incoming it will mute him. 
Anyways Noted a point if no restrict perms delete messages. 

And i have an Idea but dunno if it will work or not:
I was thinking of making something like a ban lock by utilizing Raw Function Named [GetAdminLog](https://docs.pyrogram.org/telegram/functions/channels/get-admin-log) to detect for unmutes/unbans and make a plugin like Ban Locks. Maybe @rking32 can help 🌚

**Comment by nischay03654** [comment]
> > > > > what is `gmute`
> > > > > any brief explain ?
> > > > 
> > > > 
> > > > Ahh it is like gban... Suppose you are admin in 10 groups and u gmuted a person which is also in those 10 groups... So whenever that person posts anything in those groups, the userbot will delete his message asap(need to be admin first) I saw this feature in many telegram userbots like x-tra. Please try to add this feature, it will really help us.. appreciate your work
> > > > -Thanks
> > > 
> > > 
> > > This can be done by:
> > > 
> > > 1. Adding Incoming Filter to current gban Module.
> > > 2. If user is not and admin in current common chats. Mute him directly.
> > > 3. If user tends to be an admin delete his incoming messages (if you are not the creator or admin is not promoted by you)
> > 
> > 
> > But the problem is if you are an admin and mute a person in a chat, so any other admin can unmute him as u know but if we have delete message permission in that chat we can just delete every message he post... And this cannot be stopped by anyone unless or until your delete message permission is removed.
> 
> Lelz if admin umutes user. As soon as userbot detects incoming it will mute him.
> Anyways Noted a point if no restrict perms delete messages.
> 
> And i have an Idea but dunno if it will work or not:
> I was thinking of making something like a ban lock by utilizing Raw Function Named [GetAdminLog](https://docs.pyrogram.org/telegram/functions/channels/get-admin-log) to detect for unmutes/unbans and make a plugin. Maybe @rking32 can help

I've saw this in many userbots... If u need that python script I can give you so you can understand the point... My telegram username @nischay_raj

**Comment by pboy192** [comment]
> Can u please add the gmute function in this.
> Or if it is already added tell me how to use that.
> -Thanks

@rking32 @Phyco-Ninja see this script https://github.com/StarkGang/FridayUserbot/blob/master/userbot/plugins/gmute.py
Please try to add this if u can... Its a request :)

**Comment by rking32** [comment]
@pboy192 done.
thanks for @Krishna-Singhal's PR
